channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - tensorflow==2.18.0
  - keras==3.14.1
  - numpy==2.0.2
  - scikit-learn==1.9.0
  - keras-tuner==1.4.8
  - mlflow==2.19.0  
  - pandas==2.3.3
  - matplotlib==3.11.0
  - tqdm==4.68.3
  - protobuf==5.29.6
name: mlflow-env