name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:           # <--- Tambahkan blok ini
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12.7"
          
      - name: Install MLflow
        run: pip install mlflow==2.19.0
          
      # Run as a mlflow project
      - name: Run mlflow project
        env:
          MLFLOW_ALLOW_FILE_STORE: true
        run: |
          export PATH="$CONDA/bin:$PATH"
          # Jalankan server MLflow di background pada port 5000
          mlflow server --host 127.0.0.1 --port 5000 &
          # Beri jeda 3 detik agar server siap menerima koneksi
          sleep 3
          # Jalankan project Anda
          mlflow run MLproject --env-manager=conda --experiment-name="coffeebeans-classification" -P n_filters=32 -P filter_size="3,3" -P activation="relu" -P input_shape="150,150,1" -P dense_1=128 -P dense_2=64
      
      - name: Commit and Push MLflow Artifacts to LFS
        run: |
          # 1. Konfigurasi identitas Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 2. Inisialisasi Git LFS di dalam Runner Actions
          git lfs install
          
          # 3. Daftarkan jenis file besar yang ingin dimasukkan ke LFS otomatis
          # Anda bisa menambah ekstensi lain seperti *.pkl, *.pt, *.keras sesuai kebutuhan
          git lfs track "mlruns/**/*.h5"
          git lfs track "mlruns/**/*.pkl"
          git lfs track "mlruns/**/*.keras"
          git lfs track "mlruns/**/artifacts/**"
          
          # 4. Tambahkan file .gitattributes (tempat tracking LFS disimpan) dan folder mlruns
          git add .gitattributes
          git add mlruns/
          
          # 5. Commit dan Push ke GitHub
          git commit -m "Auto-update MLflow large artifacts via Git LFS [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main